export const assistantMutationToolNormalizationSource = [
        'import { tool } from "@opencode-ai/plugin"',
        '',
        'const RESERVED_ROOT_PATHS = new Set(["SKILL.md", "draft.json"])',
        '',
        'function isRecord(value) {',
        '  return !!value && typeof value === "object" && !Array.isArray(value)',
        '}',
        '',
        'function isNonEmptyString(value) {',
        '  return typeof value === "string" && value.trim().length > 0',
        '}',
        '',
        'function isFiniteNumber(value) {',
        '  return typeof value === "number" && Number.isFinite(value)',
        '}',
        '',
        'function isPositiveFiniteNumber(value) {',
        '  return isFiniteNumber(value) && value > 0',
        '}',
        '',
        'function normalizeOptionalString(value, options) {',
        '  if (typeof value === "string") {',
        '    const trimmed = value.trim()',
        '    return trimmed ? trimmed : undefined',
        '  }',
        '  if (options?.allowNull && value === null) return null',
        '  return value === undefined ? undefined : value',
        '}',
        '',
        'function normalizeOptionalStringArray(value) {',
        '  if (!Array.isArray(value)) return value === undefined ? undefined : value',
        '  return value.map((entry) => (typeof entry === "string" ? entry.trim() : entry)).filter((entry) => entry !== "")',
        '}',
        '',
        'function normalizeDraftBlueprintCandidate(value) {',
        '  if (!isRecord(value)) return value === undefined ? undefined : value',
        '  const normalizedTags = normalizeOptionalStringArray(value.tags)',
        '  const normalized = {',
        '    ...(normalizeOptionalString(value.ref) !== undefined ? { ref: normalizeOptionalString(value.ref) } : {}),',
        '    ...(normalizeOptionalString(value.name) !== undefined ? { name: normalizeOptionalString(value.name) } : {}),',
        '    ...(normalizeOptionalString(value.content) !== undefined ? { content: normalizeOptionalString(value.content) } : {}),',
        '    ...(normalizeOptionalString(value.slug) !== undefined ? { slug: normalizeOptionalString(value.slug) } : {}),',
        '    ...(normalizeOptionalString(value.description) !== undefined ? { description: normalizeOptionalString(value.description) } : {}),',
        '    ...(Array.isArray(normalizedTags) && normalizedTags.length > 0 ? { tags: normalizedTags } : {}),',
        '    ...(value.openEditor === true ? { openEditor: true } : {}),',
        '  }',
        '  return Object.keys(normalized).length === 0 ? undefined : normalized',
        '}',
        '',
        'function hasMeaningfulDraftBlueprint(value) {',
        '  return isRecord(normalizeDraftBlueprintCandidate(value))',
        '}',
        '',
        'function normalizeModelBlueprintCandidate(value) {',
        '  if (!isRecord(value)) return value === undefined || value === null ? value : value',
        '  const provider = normalizeOptionalString(value.provider)',
        '  const modelId = normalizeOptionalString(value.modelId)',
        '  if (!provider && !modelId) return undefined',
        '  return {',
        '    ...(provider !== undefined ? { provider } : {}),',
        '    ...(modelId !== undefined ? { modelId } : {}),',
        '  }',
        '}',
        '',
        'function normalizeRelationBlueprintCandidate(value) {',
        '  if (!isRecord(value)) return value === undefined ? undefined : value',
        '  return {',
        '    ...value,',
        '    sourceParticipantKey: normalizeOptionalString(value.sourceParticipantKey),',
        '    sourceAgentId: normalizeOptionalString(value.sourceAgentId),',
        '    sourceAgentRef: normalizeOptionalString(value.sourceAgentRef),',
        '    sourceAgentName: normalizeOptionalString(value.sourceAgentName),',
        '    targetParticipantKey: normalizeOptionalString(value.targetParticipantKey),',
        '    targetAgentId: normalizeOptionalString(value.targetAgentId),',
        '    targetAgentRef: normalizeOptionalString(value.targetAgentRef),',
        '    targetAgentName: normalizeOptionalString(value.targetAgentName),',
        '    name: normalizeOptionalString(value.name),',
        '    description: normalizeOptionalString(value.description),',
        '  }',
        '}',
        '',
        'function normalizeAgentActionCandidate(action) {',
        '  return {',
        '    ...action,',
        '    model: normalizeModelBlueprintCandidate(action.model),',
        '    modelVariant: normalizeOptionalString(action.modelVariant, { allowNull: true }),',
        '    description: normalizeOptionalString(action.description, { allowNull: true }),',
        '    addSkillUrns: normalizeOptionalStringArray(action.addSkillUrns),',
        '    addSkillDraftIds: normalizeOptionalStringArray(action.addSkillDraftIds),',
        '    addSkillDraftRefs: normalizeOptionalStringArray(action.addSkillDraftRefs),',
        '    addSkillDrafts: Array.isArray(action.addSkillDrafts)',
        '      ? action.addSkillDrafts.map((draft) => normalizeDraftBlueprintCandidate(draft)).filter((draft) => draft !== undefined)',
        '      : action.addSkillDrafts,',
        '    removeSkillUrns: normalizeOptionalStringArray(action.removeSkillUrns),',
        '    removeSkillDraftIds: normalizeOptionalStringArray(action.removeSkillDraftIds),',
        '    addMcpServerNames: normalizeOptionalStringArray(action.addMcpServerNames),',
        '    removeMcpServerNames: normalizeOptionalStringArray(action.removeMcpServerNames),',
        '  }',
        '}',
        '',
        'function normalizeShowAgentActionCandidate(action) {',
        '  return {',
        '    ...action,',
        '    agentId: normalizeOptionalString(action.agentId),',
        '    agentRef: normalizeOptionalString(action.agentRef),',
        '    agentName: normalizeOptionalString(action.agentName),',
        '    editorFocus: normalizeOptionalString(action.editorFocus),',
        '  }',
        '}',
        '',
        'function normalizeShowTeamActionCandidate(action) {',
        '  return {',
        '    ...action,',
        '    teamId: normalizeOptionalString(action.teamId),',
        '    teamRef: normalizeOptionalString(action.teamRef),',
        '    teamName: normalizeOptionalString(action.teamName),',
        '    participantKey: normalizeOptionalString(action.participantKey),',
        '    relationId: normalizeOptionalString(action.relationId),',
        '  }',
        '}',
        '',
        'function normalizeShowDraftActionCandidate(action) {',
        '  return {',
        '    ...action,',
        '    draftId: normalizeOptionalString(action.draftId),',
        '    draftRef: normalizeOptionalString(action.draftRef),',
        '    draftName: normalizeOptionalString(action.draftName),',
        '  }',
        '}',
        '',
        'function normalizeStudioNodeActionCandidate(action) {',
        '  return action.nodeType === "agent"',
        '    ? normalizeShowAgentActionCandidate(action)',
        '    : normalizeShowTeamActionCandidate(action)',
        '}',
        '',
        'function normalizeAssistantActionCandidate(action) {',
        '  if (!isRecord(action) || !isNonEmptyString(action.type)) return action',
        '  switch (action.type) {',
        '    case "createAgent":',
        '    case "updateAgent":',
        '      return normalizeAgentActionCandidate(action)',
        '    case "createTeam":',
        '      return {',
        '        ...action,',
        '        description: normalizeOptionalString(action.description),',
        '        teamRules: normalizeOptionalStringArray(action.teamRules),',
        '        participantAgentIds: normalizeOptionalStringArray(action.participantAgentIds),',
        '        participantAgentRefs: normalizeOptionalStringArray(action.participantAgentRefs),',
        '        participantAgentNames: normalizeOptionalStringArray(action.participantAgentNames),',
        '        relations: Array.isArray(action.relations)',
        '          ? action.relations.map((relation) => normalizeRelationBlueprintCandidate(relation)).filter((relation) => relation !== undefined)',
        '          : action.relations,',
        '      }',
        '    case "connectAgents":',
        '      return normalizeRelationBlueprintCandidate(action)',
        '    case "showAgent":',
        '      return normalizeShowAgentActionCandidate(action)',
        '    case "showTeam":',
        '      return normalizeShowTeamActionCandidate(action)',
        '    case "showDraft":',
        '      return normalizeShowDraftActionCandidate(action)',
        '    case "setStudioNodeVisibility":',
        '    case "setStudioNodeFrame":',
        '      return normalizeStudioNodeActionCandidate(action)',
        '    default:',
        '      return action',
        '  }',
        '}',
        '',
        'function normalizeAssistantActionEnvelope(envelope) {',
        '  if (!isRecord(envelope) || !Array.isArray(envelope.actions)) return envelope',
        '  return {',
        '    ...envelope,',
        '    actions: envelope.actions.map((action) => normalizeAssistantActionCandidate(action)),',
        '  }',
        '}',
        '',
        'function normalizeAssistantBundlePath(value) {',
        '  if (typeof value !== "string") return null',
        '  const normalized = value.trim().replace(/\\\\/g, "/").replace(/^\\.\\/+/, "")',
        '  if (!normalized || normalized.includes("\\\\0")) return null',
        '  if (normalized.startsWith("/") || /^[a-zA-Z]:\\//.test(normalized)) return null',
        '  const parts = normalized.split("/").filter(Boolean)',
        '  if (parts.length === 0) return null',
        '  if (parts.some((part) => part === "." || part === "..")) return null',
        '  const joined = parts.join("/")',
        '  if (RESERVED_ROOT_PATHS.has(joined)) return null',
        '  return joined',
        '}',
        '',
]
