export const assistantMutationToolExecuteSource = [
        'export default tool({',
        '  description: "Apply APM Studio workspace mutations or UI operations. Use this tool instead of pasting raw mutation JSON into the assistant reply. Call it only when the user explicitly wants canvas, UI, or draft changes.",',
        '  args: {',
        '    version: tool.schema.literal(1).describe("Assistant action envelope version."),',
        '    actions: tool.schema.array(actionSchema).min(1).describe("Ordered APM Studio mutation actions to apply. Keep dependent actions in execution order."),',
        '  },',
        '  async execute(args, context) {',
        '    const normalizedArgs = normalizeAssistantActionEnvelope(args)',
        '    const lintIssues = lintAssistantActionEnvelope(normalizedArgs)',
        '    const lintErrors = lintIssues.filter((issue) => issue.level === "error")',
        '    if (lintErrors.length > 0) {',
        '      throw new Error([',
        '        "apply_studio_actions rejected the mutation envelope.",',
        '        ...lintErrors.map((issue) => `- action #${issue.actionIndex + 1}: ${issue.message}`),',
        '      ].join("\\n"))',
        '    }',
        '    const lintWarnings = lintIssues.filter((issue) => issue.level === "warning")',
        '    const count = Array.isArray(normalizedArgs.actions) ? normalizedArgs.actions.length : 0',
        '    context.metadata({',
        '      title: count === 1 ? "Apply Studio change" : `Apply ${count} Studio changes`,',
        '      metadata: {',
        '        studioAssistantMutation: true,',
        '        studioActionCount: count,',
        '        studioLintWarnings: lintWarnings.map((issue) => ({',
        '          actionIndex: issue.actionIndex,',
        '          message: issue.message,',
        '        })),',
        '      },',
        '    })',
        '    return count === 1',
        '      ? "Queued 1 Studio change for Studio to apply."',
        '      : `Queued ${count} Studio changes for Studio to apply.`',
        '  },',
        '})',
        '',
]
