export const assistantMutationToolSchemaSource = [
        'const stringArray = tool.schema.array(tool.schema.string())',
        'const optionalStringArray = stringArray.optional()',
        'const draftBlueprintSchema = tool.schema.object({',
        '  ref: tool.schema.string().optional(),',
        '  name: tool.schema.string(),',
        '  content: tool.schema.string(),',
        '  slug: tool.schema.string().optional(),',
        '  description: tool.schema.string().optional(),',
        '  tags: optionalStringArray,',
        '  openEditor: tool.schema.boolean().optional(),',
        '})',
        'const modelBlueprintSchema = tool.schema.object({',
        '  provider: tool.schema.string(),',
        '  modelId: tool.schema.string(),',
        '})',
        'const subscriptionsSchema = tool.schema.object({',
        '  messagesFromParticipantKeys: optionalStringArray,',
        '  messagesFromAgentIds: optionalStringArray,',
        '  messagesFromAgentRefs: optionalStringArray,',
        '  messagesFromAgentNames: optionalStringArray,',
        '  messageTags: optionalStringArray,',
        '  callboardKeys: optionalStringArray,',
        '  eventTypes: tool.schema.array(tool.schema.literal("runtime.idle")).optional(),',
        '})',
        'const safetySchema = tool.schema.object({',
        '  maxEvents: tool.schema.number().finite().nonnegative().optional(),',
        '  maxMessagesPerPair: tool.schema.number().finite().nonnegative().optional(),',
        '  maxBoardUpdatesPerKey: tool.schema.number().finite().nonnegative().optional(),',
        '  quietWindowMs: tool.schema.number().finite().nonnegative().optional(),',
        '  threadTimeoutMs: tool.schema.number().finite().nonnegative().optional(),',
        '  loopDetectionThreshold: tool.schema.number().finite().nonnegative().optional(),',
        '})',
        'const relationBlueprintSchema = tool.schema.object({',
        '  sourceParticipantKey: tool.schema.string().optional(),',
        '  sourceAgentId: tool.schema.string().optional(),',
        '  sourceAgentRef: tool.schema.string().optional(),',
        '  sourceAgentName: tool.schema.string().optional(),',
        '  targetParticipantKey: tool.schema.string().optional(),',
        '  targetAgentId: tool.schema.string().optional(),',
        '  targetAgentRef: tool.schema.string().optional(),',
        '  targetAgentName: tool.schema.string().optional(),',
        '  direction: tool.schema.enum(["both", "one-way"]).optional(),',
        '  name: tool.schema.string(),',
        '  description: tool.schema.string(),',
        '})',
        'const agentFieldsSchema = {',
        '  model: modelBlueprintSchema.nullable().optional(),',
        '  modelVariant: tool.schema.string().nullable().optional(),',
        '  description: tool.schema.string().nullable().optional(),',
        '  addSkillUrns: optionalStringArray,',
        '  addSkillDraftIds: optionalStringArray,',
        '  addSkillDraftRefs: optionalStringArray,',
        '  addSkillDrafts: tool.schema.array(draftBlueprintSchema).optional(),',
        '  removeSkillUrns: optionalStringArray,',
        '  removeSkillDraftIds: optionalStringArray,',
        '  addMcpServerNames: optionalStringArray,',
        '  removeMcpServerNames: optionalStringArray,',
        '}',
        'const locatorFields = {',
        '  teamId: tool.schema.string().optional(),',
        '  teamRef: tool.schema.string().optional(),',
        '  teamName: tool.schema.string().optional(),',
        '}',
        'const agentLocatorFields = {',
        '  agentId: tool.schema.string().optional(),',
        '  agentRef: tool.schema.string().optional(),',
        '  agentName: tool.schema.string().optional(),',
        '}',
        'const nodePositionSchema = tool.schema.object({',
        '  x: tool.schema.number().finite(),',
        '  y: tool.schema.number().finite(),',
        '})',
        'const nodeSizeSchema = tool.schema.object({',
        '  width: tool.schema.number().finite().positive(),',
        '  height: tool.schema.number().finite().positive(),',
        '})',
        'const nodeFramePatchFields = {',
        '  position: nodePositionSchema.optional(),',
        '  size: nodeSizeSchema.optional(),',
        '}',
        'const actionSchema = tool.schema.discriminatedUnion("type", [',
        '  tool.schema.object({ type: tool.schema.literal("createInstructionDraft"), ref: tool.schema.string().optional(), name: tool.schema.string(), content: tool.schema.string(), slug: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray, openEditor: tool.schema.boolean().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateInstructionDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), name: tool.schema.string().optional(), content: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteInstructionDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("createSkillDraft"), ref: tool.schema.string().optional(), name: tool.schema.string(), content: tool.schema.string(), slug: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray, openEditor: tool.schema.boolean().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateSkillDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), name: tool.schema.string().optional(), content: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteSkillDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("upsertSkillBundleFile"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), path: tool.schema.string().refine((value) => normalizeAssistantBundlePath(value) !== null, "Bundle path must stay within the draft bundle."), content: tool.schema.string() }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteSkillBundleEntry"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), path: tool.schema.string().refine((value) => normalizeAssistantBundlePath(value) !== null, "Bundle path must stay within the draft bundle.") }),',
        '  tool.schema.object({ type: tool.schema.literal("createAgent"), ref: tool.schema.string().optional(), name: tool.schema.string(), ...agentFieldsSchema }),',
        '  tool.schema.object({ type: tool.schema.literal("updateAgent"), ...agentLocatorFields, name: tool.schema.string().optional(), ...agentFieldsSchema }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteAgent"), ...agentLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("createTeam"), ref: tool.schema.string().optional(), name: tool.schema.string(), description: tool.schema.string().optional(), teamRules: optionalStringArray, safety: safetySchema.optional(), participantAgentIds: optionalStringArray, participantAgentRefs: optionalStringArray, participantAgentNames: optionalStringArray, relations: tool.schema.array(relationBlueprintSchema).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateTeam"), ...locatorFields, name: tool.schema.string().optional(), description: tool.schema.string().optional(), teamRules: optionalStringArray, safety: safetySchema.nullable().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteTeam"), ...locatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("attachAgentToTeam"), ...locatorFields, ...agentLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("detachParticipantFromTeam"), ...locatorFields, participantKey: tool.schema.string().optional(), ...agentLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("updateParticipantSubscriptions"), ...locatorFields, participantKey: tool.schema.string().optional(), ...agentLocatorFields, subscriptions: subscriptionsSchema.nullable() }),',
        '  tool.schema.object({ type: tool.schema.literal("connectAgents"), ...locatorFields, sourceParticipantKey: tool.schema.string().optional(), sourceAgentId: tool.schema.string().optional(), sourceAgentRef: tool.schema.string().optional(), sourceAgentName: tool.schema.string().optional(), targetParticipantKey: tool.schema.string().optional(), targetAgentId: tool.schema.string().optional(), targetAgentRef: tool.schema.string().optional(), targetAgentName: tool.schema.string().optional(), direction: tool.schema.enum(["both", "one-way"]).optional(), name: tool.schema.string(), description: tool.schema.string() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateRelation"), ...locatorFields, relationId: tool.schema.string(), name: tool.schema.string().optional(), description: tool.schema.string().optional(), direction: tool.schema.enum(["both", "one-way"]).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("removeRelation"), ...locatorFields, relationId: tool.schema.string() }),',
        '  tool.schema.object({ type: tool.schema.literal("showAgent"), ...agentLocatorFields, surface: tool.schema.enum(["canvas", "editor"]).optional(), reveal: tool.schema.boolean().optional(), editorFocus: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("showTeam"), ...locatorFields, surface: tool.schema.enum(["canvas", "editor"]).optional(), reveal: tool.schema.boolean().optional(), editorMode: tool.schema.enum(["team", "participant", "relation"]).optional(), participantKey: tool.schema.string().optional(), relationId: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("showDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), kind: tool.schema.enum(["instruction", "skill"]).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("setStudioNodeVisibility"), nodeType: tool.schema.enum(["agent", "team"]), visible: tool.schema.boolean(), ...locatorFields, ...agentLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("setStudioNodeFrame"), nodeType: tool.schema.enum(["agent", "team"]), ...nodeFramePatchFields, ...locatorFields, ...agentLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("setStudioPanel"), panel: tool.schema.enum(["packages", "workspaceTracking", "terminal"]), open: tool.schema.boolean() }),',
        '])',
        '',
]
