export const assistantMutationToolLintSource = [
        'function pushIssue(issues, level, actionIndex, message) {',
        '  issues.push({ level, actionIndex, message })',
        '}',
        '',
        'function registerNamedRef(issues, actionIndex, refs, namespace, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  if (refs.has(value)) {',
        '    pushIssue(issues, "error", actionIndex, `${namespace} ref "${value}" is declared more than once in the same tool call.`)',
        '    return',
        '  }',
        '  refs.add(value)',
        '}',
        '',
        'function registerDraftRef(issues, actionIndex, refs, kind, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  const existingKind = refs.get(value)',
        '  if (existingKind) {',
        '    pushIssue(issues, "error", actionIndex, `draft ref "${value}" is already declared for a ${existingKind} draft earlier in the same tool call.`)',
        '    return',
        '  }',
        '  refs.set(value, kind)',
        '}',
        '',
        'function requireNamedRef(issues, actionIndex, refs, namespace, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  if (!refs.has(value)) {',
        '    pushIssue(issues, "error", actionIndex, `${namespace} ref "${value}" is used before it is created in the same tool call.`)',
        '  }',
        '}',
        '',
        'function requireDraftRef(issues, actionIndex, refs, kind, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  const existingKind = refs.get(value)',
        '  if (!existingKind) {',
        '    pushIssue(issues, "error", actionIndex, `${kind} draft ref "${value}" is used before it is created in the same tool call.`)',
        '    return',
        '  }',
        '  if (existingKind !== kind) {',
        '    pushIssue(issues, "error", actionIndex, `${kind} draft ref "${value}" resolves to a ${existingKind} draft in the same tool call.`)',
        '  }',
        '}',
        '',
        'function requireAnyDraftRef(issues, actionIndex, refs, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  if (!refs.has(value)) {',
        '    pushIssue(issues, "error", actionIndex, `draft ref "${value}" is used before it is created in the same tool call.`)',
        '  }',
        '}',
        '',
        'function hasAgentLocator(action) {',
        '  return isNonEmptyString(action.agentId) || isNonEmptyString(action.agentRef) || isNonEmptyString(action.agentName)',
        '}',
        '',
        'function hasTeamLocator(action) {',
        '  return isNonEmptyString(action.teamId) || isNonEmptyString(action.teamRef) || isNonEmptyString(action.teamName)',
        '}',
        '',
        'function hasFramePatch(action) {',
        '  const position = action.position',
        '  const size = action.size',
        '  const hasPosition = position !== undefined',
        '  const hasSize = size !== undefined',
        '  const validPosition = !hasPosition || (isRecord(position) && isFiniteNumber(position.x) && isFiniteNumber(position.y))',
        '  const validSize = !hasSize || (isRecord(size) && isPositiveFiniteNumber(size.width) && isPositiveFiniteNumber(size.height))',
        '  return (hasPosition || hasSize) && validPosition && validSize',
        '}',
        '',
        'function lintAgentFields(actionIndex, fields, refState, issues) {',
        '  if (Array.isArray(fields.addSkillDraftRefs)) {',
        '    for (const draftRef of fields.addSkillDraftRefs) {',
        '      requireDraftRef(issues, actionIndex, refState.drafts, "skill", draftRef)',
        '    }',
        '  }',
        '}',
        '',
        'function lintRelationRefs(actionIndex, relation, refState, issues) {',
        '  requireNamedRef(issues, actionIndex, refState.agents, "agent", relation.sourceAgentRef)',
        '  requireNamedRef(issues, actionIndex, refState.agents, "agent", relation.targetAgentRef)',
        '}',
        '',
        'function registerInlineDraftRefs(actionIndex, fields, refState, issues) {',
        '  if (Array.isArray(fields.addSkillDrafts)) {',
        '    for (const draft of fields.addSkillDrafts) {',
        '      if (isRecord(draft)) {',
        '        registerDraftRef(issues, actionIndex, refState.drafts, "skill", draft.ref)',
        '      }',
        '    }',
        '  }',
        '}',
        '',
        'const BUNDLE_STABLE_PATH_ROOTS = new Set(["assets", "references", "scripts"])',
        '',
        'function hasRandomLookingFilenameSuffix(filePath) {',
        '  if (!isNonEmptyString(filePath)) return false',
        '  const parts = filePath.replace(/\\\\/g, "/").split("/").filter(Boolean)',
        '  if (parts.length < 2 || !BUNDLE_STABLE_PATH_ROOTS.has(parts[0])) return false',
        '  const basename = parts[parts.length - 1]',
        '  const stem = basename.replace(/\\.[^.]+$/, "")',
        '  const match = stem.match(/[-_]([a-z0-9]{5,12})$/i)',
        '  if (!match) return false',
        '  const suffix = match[1]',
        '  if (/^\\d+$/.test(suffix)) return false',
        '  if (/^v\\d+$/i.test(suffix)) return false',
        '  return /[a-z]/i.test(suffix) && (/\\d/.test(suffix) || /^[a-f0-9]{7,12}$/i.test(suffix))',
        '}',
        '',
        'function lintAssistantActionEnvelope(envelope) {',
        '  const refState = { agents: new Set(), teams: new Set(), drafts: new Map() }',
        '  const issues = []',
        '  for (const [actionIndex, action] of envelope.actions.entries()) {',
        '    switch (action.type) {',
        '      case "createInstructionDraft":',
        '        registerDraftRef(issues, actionIndex, refState.drafts, "instruction", action.ref)',
        '        break',
        '      case "updateInstructionDraft":',
        '      case "deleteInstructionDraft":',
        '        requireDraftRef(issues, actionIndex, refState.drafts, "instruction", action.draftRef)',
        '        break',
        '      case "createSkillDraft":',
        '        registerDraftRef(issues, actionIndex, refState.drafts, "skill", action.ref)',
        '        break',
        '      case "updateSkillDraft":',
        '      case "deleteSkillDraft":',
        '      case "deleteSkillBundleEntry":',
        '        requireDraftRef(issues, actionIndex, refState.drafts, "skill", action.draftRef)',
        '        break',
        '      case "upsertSkillBundleFile":',
        '        requireDraftRef(issues, actionIndex, refState.drafts, "skill", action.draftRef)',
        '        if (hasRandomLookingFilenameSuffix(action.path)) {',
        '          pushIssue(issues, "error", actionIndex, "Skill bundle paths must use stable filenames. Remove random, hash, timestamp, or cache-busting suffixes from assets, references, and scripts unless the user explicitly asked for versioned files.")',
        '        }',
        '        break',
        '      case "createAgent":',
        '        lintAgentFields(actionIndex, action, refState, issues)',
        '        registerNamedRef(issues, actionIndex, refState.agents, "agent", action.ref)',
        '        registerInlineDraftRefs(actionIndex, action, refState, issues)',
        '        break',
        '      case "updateAgent":',
        '        requireNamedRef(issues, actionIndex, refState.agents, "agent", action.agentRef)',
        '        lintAgentFields(actionIndex, action, refState, issues)',
        '        registerInlineDraftRefs(actionIndex, action, refState, issues)',
        '        break',
        '      case "deleteAgent":',
        '        requireNamedRef(issues, actionIndex, refState.agents, "agent", action.agentRef)',
        '        break',
        '      case "createTeam": {',
        '        const participantCount = (action.participantAgentRefs?.length || 0) + (action.participantAgentIds?.length || 0) + (action.participantAgentNames?.length || 0)',
        '        if ((action.relations?.length || 0) === 0 && participantCount >= 2) {',
        '          pushIssue(issues, "warning", actionIndex, "createTeam has multiple participants but no relations. This often produces a disconnected workflow.")',
        '        }',
        '        for (const agentRef of action.participantAgentRefs || []) {',
        '          requireNamedRef(issues, actionIndex, refState.agents, "agent", agentRef)',
        '        }',
        '        for (const relation of action.relations || []) {',
        '          lintRelationRefs(actionIndex, relation, refState, issues)',
        '        }',
        '        registerNamedRef(issues, actionIndex, refState.teams, "team", action.ref)',
        '        break',
        '      }',
        '      case "updateTeam":',
        '      case "deleteTeam":',
        '        requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        break',
        '      case "attachAgentToTeam":',
        '      case "detachParticipantFromTeam":',
        '      case "updateParticipantSubscriptions":',
        '        requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        requireNamedRef(issues, actionIndex, refState.agents, "agent", action.agentRef)',
        '        if (action.type === "updateParticipantSubscriptions" && isRecord(action.subscriptions)) {',
        '          for (const agentRef of action.subscriptions.messagesFromAgentRefs || []) {',
        '            requireNamedRef(issues, actionIndex, refState.agents, "agent", agentRef)',
        '          }',
        '        }',
        '        break',
        '      case "connectAgents":',
        '        requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        lintRelationRefs(actionIndex, action, refState, issues)',
        '        break',
        '      case "updateRelation":',
        '      case "removeRelation":',
        '        requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        break',
        '      case "showAgent":',
        '        if (!hasAgentLocator(action)) pushIssue(issues, "error", actionIndex, "showAgent needs agentId, agentRef, or agentName.")',
        '        requireNamedRef(issues, actionIndex, refState.agents, "agent", action.agentRef)',
        '        break',
        '      case "showTeam":',
        '        if (!hasTeamLocator(action)) pushIssue(issues, "error", actionIndex, "showTeam needs teamId, teamRef, or teamName.")',
        '        if (action.editorMode === "participant" && !isNonEmptyString(action.participantKey)) pushIssue(issues, "error", actionIndex, "showTeam editorMode participant needs participantKey.")',
        '        if (action.editorMode === "relation" && !isNonEmptyString(action.relationId)) pushIssue(issues, "error", actionIndex, "showTeam editorMode relation needs relationId.")',
        '        requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        break',
        '      case "showDraft":',
        '        if (action.kind === "instruction" || action.kind === "skill") {',
        '          requireDraftRef(issues, actionIndex, refState.drafts, action.kind, action.draftRef)',
        '        } else {',
        '          requireAnyDraftRef(issues, actionIndex, refState.drafts, action.draftRef)',
        '        }',
        '        break',
        '      case "setStudioNodeVisibility":',
        '        if (action.nodeType === "agent") {',
        '          if (!hasAgentLocator(action)) pushIssue(issues, "error", actionIndex, "setStudioNodeVisibility agent needs agentId, agentRef, or agentName.")',
        '          requireNamedRef(issues, actionIndex, refState.agents, "agent", action.agentRef)',
        '        } else {',
        '          if (!hasTeamLocator(action)) pushIssue(issues, "error", actionIndex, "setStudioNodeVisibility team needs teamId, teamRef, or teamName.")',
        '          requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        }',
        '        break',
        '      case "setStudioNodeFrame":',
        '        if (!hasFramePatch(action)) pushIssue(issues, "error", actionIndex, "setStudioNodeFrame needs a valid position or positive size patch.")',
        '        if (action.nodeType === "agent") {',
        '          if (!hasAgentLocator(action)) pushIssue(issues, "error", actionIndex, "setStudioNodeFrame agent needs agentId, agentRef, or agentName.")',
        '          requireNamedRef(issues, actionIndex, refState.agents, "agent", action.agentRef)',
        '        } else {',
        '          if (!hasTeamLocator(action)) pushIssue(issues, "error", actionIndex, "setStudioNodeFrame team needs teamId, teamRef, or teamName.")',
        '          requireNamedRef(issues, actionIndex, refState.teams, "team", action.teamRef)',
        '        }',
        '        break',
        '      default:',
        '        break',
        '    }',
        '  }',
        '  return issues',
        '}',
        '',
]
