export const STUDIO_RELEASE_APP_PORT = 43100
export const STUDIO_RELEASE_OPENCODE_PORT = 43102

export const STUDIO_DEV_CLIENT_PORT = 43200
export const STUDIO_DEV_API_PORT = 43201
export const STUDIO_DEV_OPENCODE_PORT = 43202

export const STUDIO_APP_PORT = STUDIO_RELEASE_APP_PORT
export const STUDIO_VITE_PORT = STUDIO_DEV_CLIENT_PORT
export const STUDIO_API_PORT = STUDIO_DEV_API_PORT
export const STUDIO_OPENCODE_PORT = STUDIO_DEV_OPENCODE_PORT
